/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     * @param titulo
     */
    public Vista(String titulo) {
        super(titulo);
        initComponents();
        setLocationRelativeTo(null);
    }

    public void addHandlerActionListenerAdivinar(ActionListener al) {
        this.jButtonSend.addActionListener(al);
        this.jTextFieldInput.addActionListener(al);
    }

    public void addHandlerActionListenerReiniciar(ActionListener al) {
        this.jButtonReset.addActionListener(al);
    }

    public void addHandlerActionListenerReglas(ActionListener al) {
        this.jButtonReglas.addActionListener(al);
    }
    
    public void informarResultado(int vidasUsadas, int numero, boolean hayVidas, String r){
        switch (r) {
                case "GANASTE":
                    this.mostrarMensaje("Ganaste! Fin del juego.\nSolo necesitaste " + vidasUsadas + " intento(s).");
                    break;
                case "MAYOR":
                    this.actualizarPista("El numero a adivinar es mayor.");
                    break;
                case "MENOR":
                    this.actualizarPista("El numero a adivinar es menor.");
                    break;
                default:
                    this.mostrarMensajeError("Ocurrio un error no esperado.");
                    break;
            }
        if (!hayVidas&&!r.equals("GANASTE")) {
                this.mostrarMensaje("Fin del juego.\nTe quedaste sin intentos.\nEl numero a adivinar era el " + numero + ".\nPISTA: El juego es imposible de perder si se utiliza la estrategia correcta.");
            }
    }
    
    
    
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "INFO", JOptionPane.INFORMATION_MESSAGE);
    }

    public String getNumeroIngresado() {
        return this.jTextFieldInput.getText();
    }

    public void actualizarPista(String pista) {
        jLabelPista.setText(pista);
    }
    
    public void limpiarNumero() {
        jTextFieldInput.setText("");
    }
    public void mostrarIntentos(int intentos){
        jLabelIntentos.setText("Le quedan "+intentos+" intentos.");
    }
    public void reiniciar(int cantVidas){
        this.actualizarPista("Nuevo juego");
        this.mostrarIntentos(cantVidas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldInput = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jLabelPista = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jButtonReglas = new javax.swing.JButton();
        jLabelInstruccion = new javax.swing.JLabel();
        jLabelIntentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setResizable(false);

        jLabelTitulo.setBackground(java.awt.Color.white);
        jLabelTitulo.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(java.awt.Color.blue);
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Bienvenido al adivinador!");

        jTextFieldInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonSend.setText("Adivinar!");
        jButtonSend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPista.setText("Nuevo juego");

        jButtonReset.setText("Reiniciar");

        jButtonReglas.setText("Reglas");

        jLabelInstruccion.setText("Ingrese su nro:");

        jLabelIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabelInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIntentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPista, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInstruccion)
                    .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonReglas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReglas;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelInstruccion;
    private javax.swing.JLabel jLabelIntentos;
    private javax.swing.JLabel jLabelPista;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldInput;
    // End of variables declaration//GEN-END:variables

}
